{{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled .Values.ingress.basicAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ws4000.fullname" . }}-ingress-basicauth
  labels:
    {{- include "ws4000.labels" . | nindent 4 }}
type: nginx.org/basic-auth
data:
  htpasswd: {{ htpasswd .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password | b64enc }}
{{- end }}
