apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ws4000.fullname" . }}-kick
  labels:
    {{- include "ws4000.labels" . | nindent 4 }}
type: Opaque
stringData:
  stream-key: {{ required "kick.streamKey is required (helm install --set kick.streamKey=YOUR_KEY)" .Values.kick.streamKey | quote }}
  rtmp-url: {{ required "kick.rtmpUrl is required (helm install --set kick.rtmpUrl=YOUR_RTMP_URL)" .Values.kick.rtmpUrl | quote }}
